# -*- coding: utf-8 -*-
"""Exploratory Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Bbo0JSg5MlfU6GzWuIemK-exwHLnIBkg
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

df = pd.read_csv('globalterrorismdb_0718dist.csv', encoding='latin1')

df.head()

df.tail()

df.shape

df.info()

df.describe()

df.corr()

df.value_counts

df.columns

df.dtypes

df.nunique()

df.rename(columns={'iyear':'Year','imonth':'Month','iday':'Day','country_txt':'Country','provstate':'State','region_txt':'Region','city': 'City', 'latitude':'Latitude', 'longitude':'Longitude', 'attacktype1_txt':'Attack_Type','target1':'Target','nkill':'Killed','nwound':'Wounded','summary':'Summary','gname':'Group','targtype1_txt':'Target_Type','weaptype1_txt':'Weapon_Type','motive':'Motive'}, inplace=True)

df=df[['Year','Month','Day','Region','Country','State','City','Latitude','Longitude','Attack_Type','Killed','Wounded','Target','Summary','Group','Target_Type','Weapon_Type','Motive']]

df['Wounded'] = df['Wounded'].fillna(0).astype(int)
df['Killed'] = df['Killed'].fillna(0).astype(int)

df.head()

plt.figure(figsize=(20, 10))
sns.countplot('Year', data=df, edgecolor='black')
plt.xticks(rotation=90)
plt.title('No. of Terrorist Activities by Year',fontsize=20)
plt.xlabel('Year', fontsize=16)
plt.ylabel('Count', fontsize=16)
plt.show()

plt.figure(figsize=(20, 10))
sns.countplot('Month', data=df, edgecolor='black')
plt.title('No. of Terrorist Activities by Month',fontsize=20)
plt.xlabel('Month', fontsize=16)
plt.ylabel('Count', fontsize=16)
plt.show()

plt.figure(figsize=(20, 10))
sns.countplot('Day', data=df, edgecolor='black')
plt.title('No. of Terrorist Activities by Day', fontsize=20)
plt.xlabel('Day', fontsize=16)
plt.ylabel('Count', fontsize=16)
plt.show()

plt.figure(figsize=(20,10))
sns.barplot(df['Region'].value_counts()[:10].index,df['Region'].value_counts()[:10].values)
plt.title('No. of Terrorist Activities by Region', fontsize=20)
plt.xlabel('Regions', fontsize=16)
plt.ylabel('Count', fontsize=16)
plt.show()

plt.figure(figsize=(20,10))
sns.barplot(df['Country'].value_counts()[:10].index,df['Country'].value_counts()[:10].values)
plt.title('No. of Terrorist Activities by Country', fontsize=20)
plt.xlabel('Countries',fontsize=16)
plt.ylabel('Count',fontsize=16)
plt.show()

plt.figure(figsize=(20,10))
sns.barplot(df['State'].value_counts()[:10].index,df['State'].value_counts()[:10].values)
plt.title('No. of Terrorist Activities by State', fontsize=20)
plt.xlabel('States',fontsize=16)
plt.ylabel('Count',fontsize=16)
plt.show()

plt.figure(figsize=(20,10))
sns.barplot(df['City'].value_counts()[1:11].index,df['City'].value_counts()[1:11].values)
plt.title('No. of Terrorist Activities by City', fontsize=20)
plt.xlabel('Cities',fontsize=16)
plt.ylabel('Count',fontsize=16)
plt.show()

plt.figure(figsize=(20, 10))
sns.countplot('Attack_Type', data=df, order=df['Attack_Type'].value_counts().index)
plt.xticks(rotation=15)
plt.title('Terrorist Activities by Attack Type', fontsize=20)
plt.xlabel('Attack Type', fontsize=16)
plt.ylabel('Count', fontsize=16)
plt.show()

plt.figure(figsize=(20, 10))
sns.countplot('Target_Type', data=df, order=df['Target_Type'].value_counts()[:10].index)
plt.xticks(rotation=15)
plt.title('Terrorist Activities by Target Type', fontsize=20)
plt.xlabel('Target Type', fontsize=16)
plt.ylabel('Count', fontsize=16)
plt.show()

plt.figure(figsize=(20,10))
sns.barplot(df['Group'].value_counts()[1:16].values, df['Group'].value_counts()[1:16].index, orient='h')
plt.title('No. of Terrorist Activities by Terrorist Group', fontsize=20)
plt.xlabel('Groups', fontsize=16)
plt.ylabel('Count', fontsize=16)
plt.show()

data = df[['Group','Country','Killed', 'Wounded']]
data = data.groupby(['Group','Country'], axis=0).sum().sort_values(['Killed', 'Wounded'], ascending=False).drop('Unknown').reset_index().head(10)
data

casualties_by_year = df.pivot_table(columns='Year', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_year

casualties_by_month = df.pivot_table(columns='Month', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_month.drop(0, axis=1)

casualties_by_day = df.pivot_table(columns='Day', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_day.drop(0, axis=1)

casualties_by_region = df.pivot_table(columns='Region', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_region

casualties_by_country = df.pivot_table(columns='Country', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_country

casualties_by_state = df.pivot_table(columns='State', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_state

casualties_by_city = df.pivot_table(columns='City', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_city

casualties_by_attack_type = df.pivot_table(columns='Attack_Type', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_attack_type

casualties_by_target_type = df.pivot_table(columns='Target_Type', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_target_type

casualties_by_group = df.pivot_table(columns='Group', values=('Killed','Wounded'), aggfunc='sum')
casualties_by_group